const cartType = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  UPDATE_CART_FROM_FIREBSE: "UPDATE_CART_FROM_FIREBSE",
  SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE"
};

export default cartType;
